variables:
  COUCHDB_USER: "admin"
  COUCHDB_PASSWORD: "my_passw0rd"

services:
  - name: couchdb:latest
    alias: localhost

image: ubuntu:20.04

before_script:
  - echo "Before script section"
  - apt update 
  - apt install -y curl apt-transport-https gnupg
  - sleep 15
  - curl http://localhost:5984/
  - curl http://localhost:5984/_users
  - chmod 755 install.sh
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"

build1:
  stage: build
  script:
    - ./install.sh

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
