### Automatic unit testing with gitlab CI is difficult
# existing couchDB instance has to run (one can use an external one, e.g. ibm)
# fileSystem operations have to be moved away from home to based on TestDirectory
# credentials of autotest have to be established
#
# test:unittest:
#     image: python:3.6
#     script:
#         - pip install numpy matplotlib scipy Pillow scikit-image opencv-python
#         - pip install pandas lmfit xlrd
#         - pip install pprint cloudant PyInquirer js2py
#         - python3 -m unittest discover -s Tests
